import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync(new URL("../site/index.html", import.meta.url), "utf8");
const body = html
  .replace(/[\s\S]*?<body[^>]*>/i, "")
  .replace(/<script[\s\S]*?<\/script>/gi, "")
  .replace(/<pre[\s\S]*?<\/pre>/gi, "")
  .replace(/<code[\s\S]*?<\/code>/gi, "")
  .replace(/<img[^>]*>/gi, "")
  .replace(/<[^>]+>/g, (tag) => /^<\/(p|h\d|li|a|button|small|figcaption|section|nav|footer)>/i.test(tag) ? "\n" : " ")
  .replace(/&amp;/g, "&").replace(/&mdash;|&#8212;/g, "—").replace(/&hellip;/g, "…").replace(/&rsquo;|&#8217;/g, "’")
  .replace(/\s*\n\s*/g, "\n");

const lines = body.split("\n")
  .flatMap((line) => line.trim().split(/(?<=[.!?…])\s+/))
  .map((line) => line.replace(/\s+/g, " ").trim())
  .filter(Boolean);
const banned = /\b(leverage|seamless|effortless|robust|powerful|intuitive|reimagine|supercharge|unlock|delightful|journey|ecosystem|AI-powered)\b/i;
const rows = lines.map((copy, index) => {
  const count = copy.match(/[\p{L}\p{N}]+(?:[-’'][\p{L}\p{N}]+)*/gu)?.length ?? 0;
  const flags = [count > 22 ? ">22 words" : "", banned.test(copy) ? "banned word" : ""].filter(Boolean).join(", ") || "—";
  return `| ${index + 1} | ${copy.replace(/\|/g, "\\|")} | ${count} | ${flags} |`;
});
const failures = rows.filter((row) => !row.endsWith("| — |"));
const output = `# Landing-page copy audit

Generated by \`node scripts/copy-audit.mjs\` on 28 August 2026. Commands are excluded.

| # | Visible text | Words | Flags |
| ---: | --- | ---: | --- |
${rows.join("\n")}

## Result

${failures.length === 0 ? "Pass: no sentence exceeds 22 words and no banned term appears." : `Fail: ${failures.length} flagged rows.`}

## Terminology

| Concept | Chosen term |
| --- | --- |
| Signed artifact | signed file list |
| Machine-readable filename | manifest.json |
| Transferred content | folder |
| Comparison differences | missing, changed, extra |
| Native application | command-line tool |
`;
writeFileSync(new URL("../.factory/copy-audit.md", import.meta.url), output);
if (failures.length) process.exitCode = 1;
